// Out-of-band worker brief — the port of planctl/brief.py's assembler + writer.
//
// `claim` assembles the brief dict and atomically writes it to
// `<state_dir>/briefs/<task_id>.json`, returning a brief_ref handle instead of
// inlining the prose. The brief is a regeneratable cache; runtime state is the
// durable truth. A missing/corrupt brief is regenerated by the next claim.
//
// The file is serialized byte-identical to Python json.dumps(indent=2,
// sort_keys=True)+newline (serializeStateJson) and written with the same
// same-dir-tmp + fsync + rename atomicity (atomicWriteRaw). It does NOT record a
// touched-path — Python's write_brief uses its own mkstemp, bypassing the
// store's touched-log, so the brief never enters the commit-staging set.

import { existsSync, readFileSync, realpathSync } from "node:fs";
import { join } from "node:path";

import { atomicWriteRaw, nowIso, serializeStateJson } from "./store.ts";

/** Brief schema version. Integer, starts at 1; additive-only within a version. */
export const BRIEF_SCHEMA_VERSION = 1;

/** Read the raw spec markdown for an epic/task id. Missing spec → empty string
 * (the briefing tolerates a spec-less entity). Mirrors brief._read_spec_md. */
function readSpecMd(dataDir: string, specId: string): string {
  const specPath = join(dataDir, "specs", `${specId}.md`);
  if (!existsSync(specPath)) {
    return "";
  }
  return readFileSync(specPath, "utf-8");
}

/** Byte cap on the glossary carried in a brief — bounds always-loaded worker
 * context. Truncation cuts at a line boundary within this cap, then appends the
 * marker below. */
export const GLOSSARY_CAP_BYTES = 16 * 1024;

/** Appended when the glossary is truncated, so the worker knows the text is
 * partial and the full glossary lives in the repo's CONTEXT.md. */
const GLOSSARY_TRUNCATION_MARKER =
  "[glossary truncated at 16KiB — read CONTEXT.md for the full text]\n";

/** Read the target repo's root CONTEXT.md glossary for a brief. Absent or
 * unreadable → "" (stable-key discipline: the field is present-but-empty, never
 * omitted). Oversize → truncated at a line boundary within GLOSSARY_CAP_BYTES
 * plus a marker line. Assembly-time only: re-read on every claim, never folded
 * into a projection, so editing CONTEXT.md needs no re-fold or migration. */
function readGlossaryMd(repoPath: string): string {
  const glossaryPath = join(repoPath, "CONTEXT.md");
  let content: string;
  try {
    content = readFileSync(glossaryPath, "utf-8");
  } catch {
    return "";
  }
  if (Buffer.byteLength(content, "utf-8") <= GLOSSARY_CAP_BYTES) {
    return content;
  }
  // Cut on a byte cap, then back up to the last line boundary so the truncation
  // lands cleanly and never splits a multibyte char (the discarded tail sits
  // after the last kept newline).
  const capped = Buffer.from(content, "utf-8")
    .subarray(0, GLOSSARY_CAP_BYTES)
    .toString("utf-8");
  const lastNl = capped.lastIndexOf("\n");
  const body = lastNl >= 0 ? capped.slice(0, lastNl + 1) : capped;
  return body + GLOSSARY_TRUNCATION_MARKER;
}

export interface BriefInputs {
  taskId: string;
  epicId: string;
  targetRepo: string;
  primaryRepo: string;
  stateRepo: string;
  tier: string | null;
  dataDir: string;
}

/** Build the brief dict from already-resolved inputs. Pure: does no discovery
 * or project resolution (callers pass resolved inputs). `snippet_context` is
 * always "" (present, not omitted) so the key set is stable. Mirrors
 * assemble_brief. */
export function assembleBrief(inputs: BriefInputs): Record<string, unknown> {
  return {
    schema_version: BRIEF_SCHEMA_VERSION,
    generated_at: nowIso(),
    task_id: inputs.taskId,
    epic_id: inputs.epicId,
    target_repo: inputs.targetRepo,
    primary_repo: inputs.primaryRepo,
    state_repo: inputs.stateRepo,
    tier: inputs.tier,
    task_spec_md: readSpecMd(inputs.dataDir, inputs.taskId),
    epic_spec_md: readSpecMd(inputs.dataDir, inputs.epicId),
    glossary_md: readGlossaryMd(inputs.targetRepo),
    snippet_context: "",
  };
}

/** Atomically write `briefDict` to `briefsDir/<task_id>.json`; return the path.
 * The briefs dir is created on demand (seed_state / init do not pre-create it).
 * Serialization + atomicity match Python's write_brief byte-for-byte. Mirrors
 * write_brief. */
export function writeBrief(
  briefsDir: string,
  taskId: string,
  briefDict: Record<string, unknown>,
): string {
  const dest = join(briefsDir, `${taskId}.json`);
  atomicWriteRaw(dest, serializeStateJson(briefDict));
  // Resolve symlinks to match Python's Path.resolve() on the returned ref —
  // the file exists post-write so realpathSync never throws.
  return realpathSync(dest);
}
