"""Consistency checks for the `queue-defer.md.tmpl` skill template (fn-595).

Mirrors `test_work_skill_consistency.py`'s pattern. The template renders two
sibling skills — `apps/planctl/skills/queue/SKILL.md` and
`apps/planctl/skills/defer/SKILL.md` — from one shared source. This module
pins the invariants that keep the two outputs in lockstep:

1. **Both rendered files exist** (after `scripts/install.sh` runs).
2. **Both carry a `Generated by:` header** pointing back to the template.
3. **Frontmatter differs only at `name:` and `description:`** — all other
   frontmatter keys (`argument-hint`, `allowed-tools`, `disable-model-invocation`)
   are byte-identical.
4. **The body diff is restricted to the variant-conditional regions** —
   the queue/defer fork should be visible only inside the documented
   variant branches (the YAML `queue_jump: true` literal, the variant
   noun, and the variant guardrail bullet).
5. **Every `planctl <verb>` in a fenced bash block resolves via `CliRunner`** —
   the verb-existence guard that bit fn-339.

The test fixture runs against the rendered files on disk; `scripts/install.sh`
must have rendered them first. The test fails loud with a hint when the
rendered files are missing.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
from click.testing import CliRunner
from planctl.cli import cli

# ---------------------------------------------------------------------------
# Paths + frozen template metadata
# ---------------------------------------------------------------------------

_REPO_PLANCTL: Path = Path(__file__).resolve().parents[1]
_TMPL_PATH: Path = _REPO_PLANCTL / "skill-templates" / "queue-defer.md.tmpl"
_QUEUE_SKILL: Path = _REPO_PLANCTL / "skills" / "queue" / "SKILL.md"
_DEFER_SKILL: Path = _REPO_PLANCTL / "skills" / "defer" / "SKILL.md"

_VARIANTS: tuple[str, ...] = ("queue", "defer")

# Multi-word verb prefixes — sourced from work_skill_consistency for symmetry.
_MULTIWORD_PREFIXES: frozenset[str] = frozenset(
    {"epic", "task", "worker", "dep", "config", "codex"}
)


# ---------------------------------------------------------------------------
# Existence + header markers
# ---------------------------------------------------------------------------


def test_skill_template_exists():
    """The source template must exist at the documented path."""
    assert _TMPL_PATH.is_file(), (
        f"{_TMPL_PATH} missing — task .3 minted this template; if absent the "
        "render fan-out has regressed"
    )


@pytest.mark.parametrize("path", [_QUEUE_SKILL, _DEFER_SKILL])
def test_rendered_skill_exists(path: Path):
    """Each variant's rendered SKILL.md must exist after `scripts/install.sh`.

    If this fires, the render fan-out didn't write to disk — either
    `scripts/lib/templates.sh` skill-variant branch regressed, or
    `scripts/install.sh` hasn't run since the template was added.
    """
    assert path.is_file(), (
        f"{path} not rendered — run `scripts/install.sh`. If install.sh ran "
        "and this still fails, scripts/lib/templates.sh skill-variant fan-out "
        "regressed."
    )


@pytest.mark.parametrize("path", [_QUEUE_SKILL, _DEFER_SKILL])
def test_rendered_skill_has_generated_by_header(path: Path):
    """Every rendered output carries a `Generated by:` header citing the
    source template path — so a future reader knows not to edit the
    generated file directly.
    """
    text = path.read_text()
    assert "Generated by: apps/planctl/skill-templates/queue-defer.md.tmpl" in text, (
        f"{path} missing `Generated by:` header — the template lost its "
        "provenance comment; restore it so future readers find the source."
    )


# ---------------------------------------------------------------------------
# Frontmatter byte-identity for shared fields
# ---------------------------------------------------------------------------


def _read_frontmatter_block(path: Path) -> str:
    """Return the raw text between the leading `---` delimiters (exclusive)."""
    text = path.read_text()
    m = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    assert m is not None, f"no frontmatter delimiter pair in {path}"
    return m.group(1)


def _parse_frontmatter_keys(block: str) -> dict[str, str]:
    """Parse top-level `key: value` lines (continuation lines folded in).

    The frontmatter is hand-curated YAML with one multi-line `description: >-`
    block; we capture each top-level key's full value (including continuation
    lines) so the test can compare field-by-field.
    """
    fm: dict[str, str] = {}
    lines = block.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        key_match = re.match(r"^([a-zA-Z_][\w-]*):\s*(.*)$", line)
        if not key_match:
            i += 1
            continue
        key = key_match.group(1)
        value_parts = [key_match.group(2)]
        i += 1
        # Fold continuation lines (indented) into the value.
        while i < len(lines) and (
            lines[i].startswith(" ") or lines[i].startswith("\t")
        ):
            value_parts.append(lines[i].strip())
            i += 1
        fm[key] = "\n".join(value_parts).strip()
    return fm


def test_frontmatter_name_differs():
    """`name:` is `plan:queue` vs `plan:defer` — the canonical variant
    differentiator. Both must be present and not equal.
    """
    queue_fm = _parse_frontmatter_keys(_read_frontmatter_block(_QUEUE_SKILL))
    defer_fm = _parse_frontmatter_keys(_read_frontmatter_block(_DEFER_SKILL))
    assert queue_fm["name"] == "plan:queue", queue_fm
    assert defer_fm["name"] == "plan:defer", defer_fm
    assert queue_fm["name"] != defer_fm["name"]


def test_frontmatter_description_differs():
    """`description:` must differ (it's the variant-specific blurb the
    Claude harness reads to decide when to auto-invoke).
    """
    queue_fm = _parse_frontmatter_keys(_read_frontmatter_block(_QUEUE_SKILL))
    defer_fm = _parse_frontmatter_keys(_read_frontmatter_block(_DEFER_SKILL))
    assert queue_fm["description"] != defer_fm["description"], (
        "queue and defer descriptions are identical — the variant fork in "
        "the frontmatter description regressed"
    )
    # And each must mention its own variant name in its blurb.
    assert "queue" in queue_fm["description"].lower()
    assert "defer" in defer_fm["description"].lower()


def test_frontmatter_shared_fields_byte_identical():
    """Every frontmatter key OTHER than `name` and `description` must be
    byte-identical across the two variants. Variant branching is documented
    to live only at those two seams (plus body conditionals).
    """
    queue_fm = _parse_frontmatter_keys(_read_frontmatter_block(_QUEUE_SKILL))
    defer_fm = _parse_frontmatter_keys(_read_frontmatter_block(_DEFER_SKILL))
    diff_keys = {"name", "description"}
    queue_shared = {k: v for k, v in queue_fm.items() if k not in diff_keys}
    defer_shared = {k: v for k, v in defer_fm.items() if k not in diff_keys}
    assert queue_shared == defer_shared, (
        "frontmatter fields outside {name, description} drifted between "
        f"queue and defer:\n  queue: {queue_shared}\n  defer: {defer_shared}"
    )


# ---------------------------------------------------------------------------
# Body diff is restricted to documented variant regions
# ---------------------------------------------------------------------------


def test_queue_skill_emits_queue_jump_yaml_literal():
    """The queue variant's embedded scaffold YAML must carry
    `queue_jump: true`. This is the load-bearing differentiator — without
    it the queue skill scaffolds the same shape as defer.
    """
    text = _QUEUE_SKILL.read_text()
    assert "queue_jump: true" in text, (
        "queue/SKILL.md does not embed `queue_jump: true` in its scaffold "
        "YAML — the variant fork in Phase 4's YAML literal regressed"
    )


def test_defer_skill_omits_queue_jump_yaml_literal():
    """The defer variant must NOT emit `queue_jump: true` anywhere — the
    documented contract is that defer omits the key entirely (defaulting to
    `false`). Any `queue_jump: true` literal in defer/SKILL.md means the
    variant conditional leaked across the fork.
    """
    text = _DEFER_SKILL.read_text()
    assert "queue_jump: true" not in text, (
        "defer/SKILL.md contains `queue_jump: true` — the defer variant must "
        "omit the key entirely; the queue-side conditional leaked"
    )


def test_both_skills_reference_planctl_scaffold():
    """Both variants must reference `planctl scaffold` as their mutation
    seam — that's the only mutating verb either skill invokes.
    """
    for path in (_QUEUE_SKILL, _DEFER_SKILL):
        assert "planctl scaffold" in path.read_text(), (
            f"{path} does not reference `planctl scaffold` — the mutation seam "
            "for both variants regressed"
        )


# ---------------------------------------------------------------------------
# Verb-existence guard (mirrors test_work_skill_consistency.py)
# ---------------------------------------------------------------------------


def _extract_planctl_verbs(skill_text: str) -> list[tuple[str, ...]]:
    """Extract every `planctl <verb>` invocation from fenced bash blocks.

    Lifted from `test_work_skill_consistency._extract_planctl_verbs` (same
    multi-word-prefix awareness, same dedupe). Returns sorted argv tuples.
    """
    verbs: set[tuple[str, ...]] = set()
    in_bash = False
    for line in skill_text.splitlines():
        stripped = line.strip()
        if stripped.startswith("```bash"):
            in_bash = True
            continue
        if stripped.startswith("```"):
            in_bash = False
            continue
        if not in_bash:
            continue
        for match in re.finditer(r"planctl\s+([\w-]+(?:\s+[\w-]+)*)", line):
            words = match.group(1).split()
            if not words:
                continue
            head = words[0]
            if head in _MULTIWORD_PREFIXES and len(words) >= 2:
                verbs.add((head, words[1]))
            else:
                verbs.add((head,))
    return sorted(verbs)


def _all_verbs() -> list[tuple[str, ...]]:
    """Union of verbs extracted from both rendered skills."""
    verbs: set[tuple[str, ...]] = set()
    for path in (_QUEUE_SKILL, _DEFER_SKILL):
        if path.is_file():
            verbs.update(_extract_planctl_verbs(path.read_text()))
    return sorted(verbs)


_VERBS: list[tuple[str, ...]] = _all_verbs()


def test_extracted_verbs_nonempty():
    """Sanity: at least one verb must surface in the union — the skills
    both embed `planctl scaffold` in a fenced bash block.
    """
    assert len(_VERBS) > 0, (
        "no planctl verbs extracted from queue/SKILL.md or defer/SKILL.md — "
        "either both files are missing or the fenced-bash extractor regressed"
    )


@pytest.mark.parametrize(
    "verb_parts",
    _VERBS,
    ids=lambda parts: "planctl-" + "-".join(parts),
)
def test_queue_defer_planctl_verbs_have_help(verb_parts: tuple[str, ...]):
    """Every `planctl <verb>` referenced in a fenced bash block of either
    rendered skill must respond to `--help` with exit code 0.

    Mirrors the fn-339 / fn-341 guard from `test_work_skill_consistency`.
    """
    result = CliRunner().invoke(cli, [*verb_parts, "--help"])
    assert result.exit_code == 0, (
        f"planctl {' '.join(verb_parts)} --help failed:\n{result.output}"
    )
