"""Out-of-band worker brief: shared assembler + atomic writer (fn-5 task .1).

The ``/plan:work`` orchestrator is content-blind — it never reasons over the
epic spec, task spec, or rendered snippet prose; it only string-substitutes
them into the worker spawn. This module moves that briefing out-of-band into a
gitignored file: ``planctl claim`` (and ``planctl worker resume``) assemble the
brief dict and atomically write it to
``<primary_repo>/.planctl/state/briefs/<task_id>.json``, returning a
``brief_ref`` handle instead of inlining the three prose fields. The worker
reads the file itself via its Read tool.

The brief is a regeneratable cache; the runtime state under ``.planctl/state/``
is the durable source of truth. A missing or corrupt brief is regenerated by
the next ``claim`` (ALREADY_MINE) or ``worker resume`` — never a fatal
inconsistency (repair-on-reclaim).

Flat single-purpose module, mirroring ``sketch_refs.py`` / ``bundle_ref.py``:
the relocated spec-read and snippet-render helpers raise a typed
:class:`BriefRenderError` instead of emitting a claim-specific error envelope,
so both ``claim`` and ``worker resume`` can translate it to their own envelope.
``assemble_brief`` / ``write_brief`` are pure — they do NOT call into any
claim-error emit path and do NOT resolve projects (claim and resume resolve
differently); callers pass already-resolved inputs.

Schema: ``schema_version`` is integer ``1``; changes within v1 are
additive-only. A reader that sees a ``schema_version`` greater than it knows
hard-fails (``brief_schema_too_new``) rather than silently mis-parsing.
"""

from __future__ import annotations

import json
import os
import subprocess
import tempfile
from pathlib import Path

#: Brief schema version. Integer, starts at 1; additive-only within a version.
BRIEF_SCHEMA_VERSION = 1


class BriefRenderError(Exception):
    """A briefing-prose fetch failed (snippet render-spec shell-out).

    Carries ``message`` + an optional ``details`` dict so each caller
    (``claim`` / ``worker resume``) can translate it to its own typed error
    envelope (e.g. claim's ``SNIPPET_RENDER_FAILED``). Raised by
    :func:`_render_snippet_context`; the spec-read helper tolerates a missing
    spec and never raises.
    """

    def __init__(self, message: str, *, details: dict | None = None) -> None:
        super().__init__(message)
        self.details = details or {}


def _render_snippet_context(task_id: str, primary_repo: str) -> str:
    """Shell ``promptctl render-spec <task_id> --format human`` with cwd=primary_repo.

    Computed BEFORE any state mutation so a render failure strands nothing.
    Empty stdout on exit 0 → ``""``; a spawn error or non-zero exit raises
    :class:`BriefRenderError`. No ``--session-id`` is passed — dedup against a
    seen-set is a worker-render concern, not the briefing fetch.
    """
    try:
        proc = subprocess.run(
            ["promptctl", "render-spec", task_id, "--format", "human"],
            cwd=str(Path(primary_repo).resolve()),
            capture_output=True,
            text=True,
            encoding="utf-8",
        )
    except OSError as exc:
        raise BriefRenderError(
            f"failed to shell promptctl render-spec for {task_id}: {exc}"
        ) from exc
    if proc.returncode != 0:
        raise BriefRenderError(
            f"promptctl render-spec exited {proc.returncode} for {task_id}",
            details={"stderr": (proc.stderr or "").strip()},
        )
    return proc.stdout


def _read_spec_md(data_dir: Path, spec_id: str) -> str:
    """Read the raw spec markdown for an epic/task id (mirrors run_cat.py).

    Missing spec → empty string (the briefing tolerates a spec-less entity;
    existence of the task JSON is already gated upstream).
    """
    spec_path = data_dir / "specs" / f"{spec_id}.md"
    if not spec_path.exists():
        return ""
    return spec_path.read_text(encoding="utf-8")


def assemble_brief(
    *,
    task_id: str,
    epic_id: str,
    target_repo: str,
    primary_repo: str,
    state_repo: str,
    tier: str | None,
    data_dir: Path,
) -> dict:
    """Build the brief dict from already-resolved inputs.

    Pure: does NOT do roots discovery or ``resolve_project()`` (``claim`` and
    ``worker resume`` resolve their owning project differently and pass the
    results in). Reads the two spec markdowns from ``data_dir`` and shells the
    snippet render (cwd=``primary_repo``); a render failure raises
    :class:`BriefRenderError` for the caller to translate.

    ``snippet_context`` is ``""`` (not omitted) when there is no substrate, so
    the brief's key set is stable across tasks with and without snippets.
    """
    from planctl.store import now_iso

    task_spec_md = _read_spec_md(data_dir, task_id)
    epic_spec_md = _read_spec_md(data_dir, epic_id)
    snippet_context = _render_snippet_context(task_id, primary_repo)

    return {
        "schema_version": BRIEF_SCHEMA_VERSION,
        "generated_at": now_iso(),
        "task_id": task_id,
        "epic_id": epic_id,
        "target_repo": target_repo,
        "primary_repo": primary_repo,
        "state_repo": state_repo,
        "tier": tier,
        "task_spec_md": task_spec_md,
        "epic_spec_md": epic_spec_md,
        "snippet_context": snippet_context,
    }


def write_brief(briefs_dir: Path, task_id: str, brief_dict: dict) -> Path:
    """Atomically write *brief_dict* to ``briefs_dir/<task_id>.json``; return the path.

    Atomicity: same-directory temp via ``mkstemp`` → ``os.replace`` (never a
    cross-device move, never a partial read). ``mkstemp`` creates the temp with
    mode ``0600`` and ``O_EXCL`` (no symlink-follow on create); we re-assert
    ``0600`` on the final path so the brief is owner-only regardless of umask.
    The temp file is cleaned up on any write failure. The destination is always
    confined under ``briefs_dir`` — a trusted local path under gitignored
    ``state/`` — so no reader-side TOCTOU hardening is warranted.

    ``briefs_dir`` is created (``parents=True, exist_ok=True``) because legacy
    projects only carry ``state/tasks`` + ``state/locks`` — ``state/briefs`` is
    not pre-created by ``init``.

    Returns the absolute path of the written brief.
    """
    briefs_dir.mkdir(parents=True, exist_ok=True)
    dest = (briefs_dir / f"{task_id}.json").resolve()
    content = json.dumps(brief_dict, indent=2, sort_keys=True) + "\n"

    fd, tmp_path = tempfile.mkstemp(dir=str(briefs_dir), suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(content)
            f.flush()
            os.fsync(f.fileno())
        os.chmod(tmp_path, 0o600)
        os.replace(tmp_path, dest)
        # fsync the parent dir so the new directory entry is durable.
        parent_fd = os.open(str(briefs_dir), os.O_RDONLY)
        try:
            os.fsync(parent_fd)
        finally:
            os.close(parent_fd)
    except Exception:
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)
        raise

    return dest
