"""Out-of-band worker brief: shared assembler + atomic writer.

The ``/plan:work`` orchestrator is content-blind — it never reasons over the
epic spec or task spec; it only string-substitutes them into the worker spawn.
This module moves that briefing out-of-band into a gitignored file: ``planctl
claim`` (and ``planctl worker resume``) assemble the brief dict and atomically
write it to ``<primary_repo>/.planctl/state/briefs/<task_id>.json``, returning a
``brief_ref`` handle instead of inlining the prose fields. The worker reads the
file itself via its Read tool.

The brief is a regeneratable cache; the runtime state under ``.planctl/state/``
is the durable source of truth. A missing or corrupt brief is regenerated by
the next ``claim`` (ALREADY_MINE) or ``worker resume`` — never a fatal
inconsistency (repair-on-reclaim).

Flat single-purpose module: the spec-read helper tolerates a missing spec and
never raises.
``assemble_brief`` / ``write_brief`` are pure — they do NOT call into any
claim-error emit path and do NOT resolve projects (claim and resume resolve
differently); callers pass already-resolved inputs.

Schema: ``schema_version`` is integer ``1``; changes within v1 are
additive-only. A reader that sees a ``schema_version`` greater than it knows
hard-fails (``brief_schema_too_new``) rather than silently mis-parsing.
"""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path

#: Brief schema version. Integer, starts at 1; additive-only within a version.
BRIEF_SCHEMA_VERSION = 1


def _read_spec_md(data_dir: Path, spec_id: str) -> str:
    """Read the raw spec markdown for an epic/task id (mirrors run_cat.py).

    Missing spec → empty string (the briefing tolerates a spec-less entity;
    existence of the task JSON is already gated upstream).
    """
    spec_path = data_dir / "specs" / f"{spec_id}.md"
    if not spec_path.exists():
        return ""
    return spec_path.read_text(encoding="utf-8")


def assemble_brief(
    *,
    task_id: str,
    epic_id: str,
    target_repo: str,
    primary_repo: str,
    state_repo: str,
    tier: str | None,
    data_dir: Path,
) -> dict:
    """Build the brief dict from already-resolved inputs.

    Pure: does NOT do roots discovery or ``resolve_project()`` (``claim`` and
    ``worker resume`` resolve their owning project differently and pass the
    results in). Reads the two spec markdowns from ``data_dir``.

    ``snippet_context`` is always ``""`` (present, not omitted) so the brief's
    key set is stable across tasks; it stays in the schema as a dormant slot
    (schema_version stays 1).
    """
    from planctl.store import now_iso

    task_spec_md = _read_spec_md(data_dir, task_id)
    epic_spec_md = _read_spec_md(data_dir, epic_id)

    return {
        "schema_version": BRIEF_SCHEMA_VERSION,
        "generated_at": now_iso(),
        "task_id": task_id,
        "epic_id": epic_id,
        "target_repo": target_repo,
        "primary_repo": primary_repo,
        "state_repo": state_repo,
        "tier": tier,
        "task_spec_md": task_spec_md,
        "epic_spec_md": epic_spec_md,
        "snippet_context": "",
    }


def write_brief(briefs_dir: Path, task_id: str, brief_dict: dict) -> Path:
    """Atomically write *brief_dict* to ``briefs_dir/<task_id>.json``; return the path.

    Atomicity: same-directory temp via ``mkstemp`` → ``os.replace`` (never a
    cross-device move, never a partial read). ``mkstemp`` creates the temp with
    mode ``0600`` and ``O_EXCL`` (no symlink-follow on create); we re-assert
    ``0600`` on the final path so the brief is owner-only regardless of umask.
    The temp file is cleaned up on any write failure. The destination is always
    confined under ``briefs_dir`` — a trusted local path under gitignored
    ``state/`` — so no reader-side TOCTOU hardening is warranted.

    ``briefs_dir`` is created (``parents=True, exist_ok=True``) because legacy
    projects only carry ``state/tasks`` + ``state/locks`` — ``state/briefs`` is
    not pre-created by ``init``.

    Returns the absolute path of the written brief.
    """
    briefs_dir.mkdir(parents=True, exist_ok=True)
    dest = (briefs_dir / f"{task_id}.json").resolve()
    content = json.dumps(brief_dict, indent=2, sort_keys=True) + "\n"

    fd, tmp_path = tempfile.mkstemp(dir=str(briefs_dir), suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(content)
            f.flush()
            os.fsync(f.fileno())
        os.chmod(tmp_path, 0o600)
        os.replace(tmp_path, dest)
        # fsync the parent dir so the new directory entry is durable.
        parent_fd = os.open(str(briefs_dir), os.O_RDONLY)
        try:
            os.fsync(parent_fd)
        finally:
            os.close(parent_fd)
    except Exception:
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)
        raise

    return dest
